name: Build Anaconda3 Alpine Image
on:
  push:
    paths:
      - 'anaconda3/alpine/Dockerfile'
      - '.github/workflows/anaconda_alpine_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/alpine/Dockerfile'
      - '.github/workflows/anaconda_alpine_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2
        with:
          version: latest
          driver-opts: network=host

      - name: build anaconda3/alpine
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: ./anaconda3/alpine
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/alpine/Dockerfile
          tags: continuumio/anaconda3/alpine:latest
          push: false
