name: Build Anaconda3 Alpine Image
on:
  push:
    tags:
      - 'anaconda3-*'
    paths:
      - 'anaconda3/alpine/Dockerfile'
      - '.github/workflows/anaconda_alpine_ci.yml'
  pull_request:
    paths:
      - 'anaconda3/alpine/Dockerfile'
      - '.github/workflows/anaconda_alpine_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@94ab11c41e45d028884a99163086648e898eed25
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@548e2346a9987b56d8a4104fe776321ff8e23440
        with:
          images: |
            continuumio/anaconda3
          tags: |
            type=ref,event=branch,suffix=-alpine
            type=ref,event=pr,suffix=-alpine
            type=match,pattern=anaconda3-(.*),group=1,suffix=-alpine
          flavor: |
            latest=false

      - name: build-push anaconda3/alpine
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./anaconda3/alpine
          builder: ${{ steps.buildx.outputs.name }}
          file: ./anaconda3/alpine/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
