name: Build and publish the concourse-rsync-resource image
on:
  push:
    branches:
      - main
    tags:
      - 'crr-*'
    paths:
      - 'concourse-rsync-resource/Dockerfile'
      - '.github/workflows/concourse_rsync_resource.yml'
  pull_request:
    paths:
      - 'concourse-rsync-resource/Dockerfile'
      - '.github/workflows/concourse_rsync_resource.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3
        with:
          submodules: true

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v2
        if: github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Public ECR
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v2
        if: github.ref == 'refs/heads/main'
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
          AWS_REGION: us-east-1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v4
        with:
          images: |
            continuumio/concourse-rsync-resource
            public.ecr.aws/y0o4y9o3/concourse-rsync-resource
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=crr-(.*),group=1

      - name: build-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v4
        with:
          context: ./concourse-rsync-resource
          builder: ${{ steps.buildx.outputs.name }}
          file: ./concourse-rsync-resource/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
