name: Build Miniconda3 Debian Image
on:
  push:
    tags:
      - 'miniconda3-v*.*.*'
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@27d0a4f181a40b142cce983c5393082c365d1480
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8b842e721d38d18bea23b57f4c040e53331f4ca2
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=miniconda3-v(.*),group=1

      - name: build miniconda3/debian
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./miniconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./miniconda3/debian/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
