name: Build Miniconda3 Nanoserver Image
on:
  push:
    tags:
      - 'miniconda3-v*.*.*-nanoserver'
    paths:
      - 'miniconda3/nanoserver/Dockerfile'
      - '.github/workflows/miniconda_nanoserver_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/nanoserver/Dockerfile'
      - '.github/workflows/miniconda_nanoserver_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Login to DockerHub
        uses: docker/login-action@bb984efc561711aaa26e433c32c3521176eae55b
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@e5622373a38e60fb6d795a4421e56882f2d7a681
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch,suffix=-nanoserver
            type=ref,event=pr,suffix=-nanoserver
            type=match,pattern=miniconda3-v(.*)-nanoserver,group=1,suffix=-nanoserver
          flavor: |
            latest=false

      # The build push action does not support windows builds yet,
      # thus using raw commands https://github.com/docker/build-push-action/issues/18
      # TODO: Parse and use the meta action generated tag list
      - name: Build
        run: |
          echo "${{ steps.meta.outputs.tags }}"
          cd miniconda3/nanoserver && docker build . -t continuumio/miniconda3:master-nanoserver && docker image inspect continuumio/miniconda3:master-nanoserver

      - name: Push
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        run: |
          cd miniconda3/nanoserver && docker push continuumio/miniconda3:master-nanoserver
