name: Build Miniconda3 Alpine Image
on:
  push:
    tags:
      - 'miniconda3-v*.*.*-alpine'
    paths:
      - 'miniconda3/alpine/Dockerfile'
      - '.github/workflows/miniconda_alpine_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/alpine/Dockerfile'
      - '.github/workflows/miniconda_alpine_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Login to DockerHub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@abe5d8f79a1606a2d3e218847032f3f2b1726ab0
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@3a3bb3a81753dc99f090d24ee7e5343838b73a96
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch,suffix=-alpine
            type=ref,event=pr,suffix=-alpine
            type=match,pattern=miniconda3-v(.*)-alpine,group=1,suffix=-alpine
          flavor: |
            latest=false

      - name: build miniconda3/alpine
        uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
        with:
          context: ./miniconda3/alpine
          builder: ${{ steps.buildx.outputs.name }}
          file: ./miniconda3/alpine/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
