name: Build Miniconda3 Debian Image
on:
  push:
    tags:
      - 'miniconda3-v*.*.*'
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Login to DockerHub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # tag=v2
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@8b122486cedac8393e77aa9734c3528886e4a1a8 # tag=v2
        with:
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@dc7b9719a96d48369863986a06765841d7ea23f6 # tag=v2
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=miniconda3-v(.*),group=1

      - name: build miniconda3/debian
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94 # tag=v3
        with:
          context: ./miniconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./miniconda3/debian/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
          push: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
