name: Build Miniconda3 Debian Image
on:
  push:
    branches:
      - main
    tags:
      - 'miniconda3-v*.*.*'
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Login to DockerHub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@5964de0df58d5ad28b04d8fe2e6b80ad47105b91 # v3.5.0
        with:
          # https://github.com/docker/setup-qemu-action/issues/188#issuecomment-2604322104
          image: tonistiigi/binfmt:qemu-v8.1.5
          platforms: linux/amd64,linux/arm64,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=miniconda3-v(.*),group=1

      - name: build miniconda3/debian
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: ./miniconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./miniconda3/debian/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
