name: Build Miniconda3 Debian Image
on:
  push:
    branches:
      - main
    tags:
      - 'miniconda3-v*.*.*'
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  pull_request:
    paths:
      - 'miniconda3/debian/Dockerfile'
      - '.github/workflows/miniconda_debian_ci.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags')
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3
        with:
          platforms: linux/amd64,linux/arm64,linux/s390x

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3
        with:
          version: latest
          driver-opts: network=host

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: continuumio/miniconda3
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=match,pattern=miniconda3-v(.*),group=1

      - name: build miniconda3/debian
        uses: docker/build-push-action@af5a7ed5ba88268d5278f7203fb52cd833f66d6e # v5
        with:
          context: ./miniconda3/debian
          builder: ${{ steps.buildx.outputs.name }}
          file: ./miniconda3/debian/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/s390x
          push: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags') }}
